[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/_framework/*"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200